services:
  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:17-alpine
    container_name: my-postgres-db
    restart: always
    environment:
      # Эти переменные используются образом Postgres для инициализации БД
      POSTGRES_DB: mywebappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: my-groovy-app
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: mywebappdb
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db
volumes:
  postgres-data: